### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by howardgriffin** [G-U-N/AnimateLCM#1]
Nice work! And when will the code be released?

**Comment by CHNxindong** [comment]
Hope the code and weight release.

**Comment by CyberTimon** [comment]
It looks so cool. I really can't wait for the code. PS: Is the code in the huggingface space not enough to work with?

**Comment by CyberTimon** [comment]
The model is here: https://huggingface.co/wangfuyun/AnimateLCM

**Comment by betterze** [comment]
How to use this model? Could you share the example code? thx a lot  https://huggingface.co/wangfuyun/AnimateLCM

**Comment by G-U-N** [comment]
Hi, every one. I just upload a beta version t2v space for your testing, see [AnimateLCM](https://huggingface.co/spaces/wangfuyun/AnimateLCM).

**Comment by CyberTimon** [comment]
Thanks for the update! I'm very hyped for the image to video release. Great work! I was always looking for a low latency solution

**Comment by betterze** [comment]
Is there a way to run it on my local machine?

**Comment by peteromallet** [comment]
Hi @G-U-N,

Congrats on this! Are there any plans to release the trainer code or train a v3 version?
