### ISSUE TITLE
Teacher-Free Adaptation is Latent Consistency Fine-tuning (LCF)?

### ISSUE THREAD

**Issue by dcfucheng** [G-U-N/AnimateLCM#10]
Great works~

I am confused about 'Teacher-Free Adaptation'. Does it mean Latent Consistency Fine-tuning (LCF)? Directly select two time steps and get nosied data z_{t} and z_{t-1}, and then directly calculate the consistency loss for these two time steps to enforce self-consistency property as LCF in LCM paper?

So the training procedure is ：
1. Train base image diffusion model, using Latent Consistency Distillation and image data.
2. Fix the lcm image diffusion weight and add a trainable temporal layer, using Latent Consistency Distillation and new Initialization strategy and video data.
3. Add other controls (controlnet or IPadpter), using Latent Consistency Fine-tuning and the data about control conditions.

Do I have an exact understanding?

**Comment by G-U-N** [comment]
Good summary! Thanks for your interest and careful reading. For the Teacher-Free Adaptation and Latent Consistency Fine-tuning, I would say that they are technically the same thing, all following the consistency-training (CT) proposed in [consistency models](https://arxiv.org/pdf/2303.01469.pdf) by Song et al. The difference is that we verify that it works for training  adapters from scratch or fine-tuning existing adapters to follow consistency property, mainly at the purpose level.
