### ISSUE TITLE
How did you train the model ?

### ISSUE THREAD

**Issue by lelapin123** [G-U-N/AnimateLCM#19]
I find this model far superior than it peers.
How did you make it like that ?

**Comment by G-U-N** [comment]
which peer do you mean?

**Comment by lelapin123** [comment]
edit wrong answer:

I mean it is better than this one:
https://civitai.com/models/108836?modelVersionId=159987
the sd15v2
It is not bad, but for LCM your is superior.
Is it just because yours is trained for LCM that makes it better?

**Comment by G-U-N** [comment]
Yeah. You can think it in that way. Also would recommend you read the paper for more details.
