### ISSUE TITLE
Training or Finetuning code

### ISSUE THREAD

**Issue by MavisHoot** [G-U-N/AnimateLCM#21]
Great work, Please will you release the training code. I will like to know when

**Comment by G-U-N** [comment]
Just release the training code for SVD, see [train_svd_lcm.py](https://github.com/G-U-N/AnimateLCM/blob/master/animatelcm_svd/train_svd_lcm.py). Thanks for the interest.

**Comment by lileilai** [comment]
> Just release the training code for SVD, see [train_svd_lcm.py](https://github.com/G-U-N/AnimateLCM/blob/master/animatelcm_svd/train_svd_lcm.py). Thanks for the interest.

Is there a plan to provide training scripts for SD15's  txt2video，Thanks.

**Comment by G-U-N** [comment]
@lileilai  All code will be released once accepted.

**Comment by lileilai** [comment]
> @lileilai All code will be released once accepted.

Thanks for your reply. I would like to do a video inpainting task based on animatediff_sd15, is it ok to  adapt the decouple consistency training ？
