### ISSUE TITLE
Hi，the motion is smooth, but video is blurry,why?

### ISSUE THREAD

**Issue by ersanliqiao** [G-U-N/AnimateLCM#23]
![image](https://github.com/G-U-N/AnimateLCM/assets/8411769/60ad78c0-2b57-4358-a24d-18de5d1b2cb2)

**Comment by ersanliqiao** [comment]
![报纸墙 可爱粉色长发少女 è 桌面壁纸_彼岸壁纸](https://github.com/G-U-N/AnimateLCM/assets/8411769/b29ae86e-a04e-47ce-8943-270a39731ae1)

https://github.com/G-U-N/AnimateLCM/assets/8411769/b2863f32-df5d-4cc6-b0ca-cb5eceb8bdb9

seems the result is unstable

**Comment by G-U-N** [comment]
Are you using the AnimateLCM-I2V?

**Comment by ersanliqiao** [comment]
Yes, SVD I2V

**Comment by G-U-N** [comment]
Yes, it is not as stable as the original SVD. Generation failure happens sometimes. Try to increase the inference steps when needed.

**Comment by ersanliqiao** [comment]
OK

**Comment by ersanliqiao** [comment]
Hi，where to download realistic1.safetensors,realistic2.safetensors?

**Comment by G-U-N** [comment]
[Realistic1](https://civitai.com/models/4201?modelVersionId=125411). 
[Realistic2](https://civitai.com/models/43331?modelVersionId=176425).
Put them in the [Personalized Folder](https://github.com/G-U-N/AnimateLCM/tree/master/animatelcm_sd15/models/Personalized).

**Comment by ersanliqiao** [comment]
> [Realistic1](https://civitai.com/models/4201?modelVersionId=125411). [Realistic2](https://civitai.com/models/43331?modelVersionId=176425). Put them in the [Personalized Folder](https://github.com/G-U-N/AnimateLCM/tree/master/animatelcm_sd15/models/Personalized).

Thank you very much!!
<img width="301" alt="截屏2024-05-09 下午3 54 01" src="https://github.com/G-U-N/AnimateLCM/assets/8411769/17ee0a28-005e-4b0c-a93b-c8074ffff376">

**Comment by G-U-N** [comment]
My pleasure : )

**Comment by ersanliqiao** [comment]
Hi, i have a question about dataset for svd, what dataset did you to train?

**Comment by G-U-N** [comment]
WebVid 2M. The implementation details on SVD are not included in the paper currently. See [issue-22](https://github.com/G-U-N/AnimateLCM/issues/22) for more training details.

**Comment by ersanliqiao** [comment]
hi，will you release sd1.5 training code of t2v and i2v?

**Comment by G-U-N** [comment]
yes, but will release them a bit later.
