### ISSUE TITLE
Image to Video generation

### ISSUE THREAD

**Issue by CyberTimon** [G-U-N/AnimateLCM#4]
Hello devs!

I would like to know if it's possible to start from an image, instead of generating the image. I have many nice images I would like to animate with this. I've skimmed the code and I couldn't find an easy way.

Thanks for the answer!
Kind regard,
Timon Käch

**Comment by G-U-N** [comment]
Yes, as we describe in the paper, it can achieve image-to-video synthesis in the open domain.  We haven't released the corresponding weights until we ensure that everything works properly.

**Comment by CyberTimon** [comment]
Thanks for the fast response! Looking forward for these weights. The results are amazing ✌️
