### ISSUE TITLE
Distillation of Video Diffusion Based Model

### ISSUE THREAD

**Issue by m-muaz** [G-U-N/AnimateLCM#8]
Hi, Firstly, Great work. 

I have a question regarding the distillation of video diffusion model. Did you used the DDIM sampler while distilling from the video based diffusion model and did the training used skip timesteps while training the online consistency distillation model?

Also, how many optimization steps did the training involved for generating good results with the distilled model?

Thanks for the help.

**Comment by G-U-N** [comment]
Yes, basically using DDIM for simplicity. You may observe good quality with only 5k steps. But  continuing training will make it better.
