### ISSUE TITLE
Possible Typo in the Paper

### ISSUE THREAD

**Issue by shampooooo** [G-U-N/AnimateLCM#9]
Hi, Thanks for the interesting paper.

I think the part shown in equation (10) should be c. If x is correct, could you tell me why?

![제목 없음](https://github.com/G-U-N/AnimateLCM/assets/95483328/f49d7d2d-ebc8-4302-82d0-af1d2a836065)

**Comment by G-U-N** [comment]
Yeah, it's a typo. Thanks for pointing it out, and I gonna correct it when revising our paper.
